= Native sample with Spring Boot 3
This sample can be used to hack on Native with Spring Boot 3.



== Setup
You need to have a `native-image` in your path.
The easiest way to get started is with SDKMan:

[indent=0]
----
	$ sdk install java 22.0.0.2.r17-nik
----

Once GraalVM is installed, you need to use it in your shell:

[indent=0]
----
	$ sdk use java 22.0.0.2.r17-nik
----

Validate that GraalVM is available in your shell:

[indent=0]
----
	$ java -version
	openjdk version "17.0.2" 2022-01-18 LTS
	OpenJDK Runtime Environment GraalVM 22.0.0.2 (build 17.0.2+9-LTS)
	OpenJDK 64-Bit Server VM GraalVM 22.0.0.2 (build 17.0.2+9-LTS, mixed mode, sharing)
----



== Building and Running
The sample can be built with Maven or Gradle.



=== Maven
To build the project and generate a native image for it, run the following command:

[indent=0]
----
	$ ./mvnw package -Pnative
----

One the build has completed, the native executable is in your `target` directory.
You can run it as follows:

[indent=0]
----
	$ target/demo-native-sample
----



=== Gradle
To build the project and generate a native image for it, run the following command:

[indent=0]
----
	$ ./gradlew nativeCompile
----

One the build has completed, the native executable is in your `build/native/nativeCompile` directory.
You can run it as follows:

[indent=0]
----
	$ build/native/nativeCompile/demo-native-sample
----


